# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - TriviaRank-FrontEnd

pool:
  vmImage: ubuntu-latest

variables:
  appDirectory: TriviaRank-FrontEnd

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: npm install
  workingDirectory: $(appDirectory)

- script: npx ng build
  displayName: ng build
  workingDirectory: $(appDirectory)

- script: npx ng lint
  displayName: ng lint
  workingDirectory: $(appDirectory)

- script: npx ng test --browsers ChromeHeadless --no-watch --code-coverage
  displayName: ng test
  workingDirectory: $(appDirectory)

- task: AzureRmWebAppDeployment@4
  displayName: app service deploy
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(3108cf2f-4c35-4864-8dad-b97042f1dd42)'
    appType: 'webApp'
    WebAppName: 'TriviaRank-Web'
    packageForLinux: '$(appDirectory)/dist/TriviaRank-FrontEnd'